### ISSUE TITLE
Legend URL missing version information from Capabilities document in GeoServer 2.20.0

### ISSUE THREAD

**Issue by kalxas** [EOFarm/geoportal.ypen.gr#10]
![image](https://user-images.githubusercontent.com/383944/139051409-07f6070a-cd89-4e84-abe4-c20ae20f27b1.png)

**Comment by kalxas** [comment]
Documentation about GetLegendGraphic: https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html

**Comment by kalxas** [comment]
Upstream issue: https://osgeo-org.atlassian.net/browse/GEOS-5472

**Comment by kalxas** [comment]
And this is the line where all happens:
https://github.com/geoserver/geoserver/blob/main/src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java#L1285

**Comment by kalxas** [comment]
Here as well:
https://github.com/geoserver/geoserver/blob/main/src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java#L1622-L1724

**Comment by kalxas** [comment]
We can add a custom Legend URL through the Styles UI:

![image](https://user-images.githubusercontent.com/383944/140924842-81cd2c84-8634-4491-a9a6-09a02ebf9696.png)

**Comment by kalxas** [comment]
@grigoriouelena shall we add a custom URL so we can test the validator?

**Comment by kalxas** [comment]
Reported upstream here: https://osgeo-org.atlassian.net/browse/GEOS-10336

**Comment by grigoriouelena** [comment]
I provided an image for the legend, through the Styles UI but geoserver still creates the GetLegendGraphic request to the WMS to provide the LegendURL/OnlineResouce element in the getcapabilities response.

It seems though that the fact that the version parameter is missing from the above URL is not the reason the test fails.

I reported the issue to the INSPIRE validation helpdesk here: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/680

**Comment by kalxas** [comment]
I guess this one is also to be closed @grigoriouelena ?
