### ISSUE TITLE
Map background

### ISSUE THREAD

**Issue by kalxas** [EOFarm/geoportal.ypen.gr#17]
We are going to evaluate the following map backgrounds for potential use:
* Open Street Map (via upstream tiles or private tile server)
* https://www.gys.gr/hmgs-geoportal.html, specifically the map layer
* https://www.ktimanet.gr/CitizenWebApp/Orthophotographs_Page.aspx (via upstream tiles or private tile server)

**Comment by kalxas** [comment]
Right now OSM is used in the development environment

**Comment by kalxas** [comment]
http://geoportal.ypen.gr/tiles is now serving tiles from ktimanet.gr

![image](https://user-images.githubusercontent.com/383944/140950523-c62f9c18-9748-4eff-89ea-acffe98bf6dc.png)

**Comment by kalxas** [comment]
![image](https://user-images.githubusercontent.com/383944/140950821-58aa41f2-b50b-4a4a-bb68-fac7338c423b.png)

**Comment by kalxas** [comment]
Potential base maps: https://eurogeographics.org/open-maps-for-europe-progress/

**Comment by kalxas** [comment]
Today we got the required links from gys.gr

**Comment by kalxas** [comment]
gys.gr layers have been configured in GeoServer as Cascaded WMTS layers:

https://docs.geoserver.org/latest/en/user/data/cascaded/wmts.html

Used as standalone layers, they work fine in QGIS.

Unfortunately SLD styling is not supported for cascaded WMTS layers so a group style like the following cannot work:

```
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.0.0" 
 xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" 
 xmlns="http://www.opengis.net/sld" 
 xmlns:ogc="http://www.opengis.net/ogc" 
 xmlns:xlink="http://www.w3.org/1999/xlink" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- a Named Layer is the basic building block of an SLD document -->
  <NamedLayer>
    <Name>CARTO_Z0_Z8</Name>
    <UserStyle>
      <Title>CARTO_Z0_Z8</Title>
      <Abstract>CARTO_Z0_Z8</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>rule1</Name>
          <MinScaleDenominator>2311162.217155</MinScaleDenominator>
          <MaxScaleDenominator>600000000.00</MaxScaleDenominator>
          <RasterSymbolizer>
            <Opacity>1.0</Opacity>
          </RasterSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
  <NamedLayer>
    <Name>CARTO_Z9_Z10_1200</Name>
    <UserStyle>
      <Title>CARTO_Z9_Z10_1200</Title>
      <Abstract>CARTO_Z9_Z10_1200</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>rule2</Name>
          <MinScaleDenominator>577790.554289</MinScaleDenominator>
          <MaxScaleDenominator>2311162.217155</MaxScaleDenominator>
          <RasterSymbolizer>
            <Opacity>1.0</Opacity>
          </RasterSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
  <NamedLayer>
    <Name>CARTO_Z11_500</Name>
    <UserStyle>
      <Title>CARTO_Z11_500</Title>
      <Abstract>CARTO_Z11_500</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>rule3</Name>
          <MinScaleDenominator>288895.277144</MinScaleDenominator>
          <MaxScaleDenominator>577790.554289</MaxScaleDenominator>
          <RasterSymbolizer>
            <Opacity>1.0</Opacity>
          </RasterSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
  <NamedLayer>
    <Name>CARTO_Z12_ERM250</Name>
    <UserStyle>
      <Title>CARTO_Z12_ERM250</Title>
      <Abstract>CARTO_Z12_ERM250</Abstract>
      <FeatureTypeStyle>
        <Rule>
          <Name>rule4</Name>
          <MinScaleDenominator>72223.819286</MinScaleDenominator>
          <MaxScaleDenominator>288895.277144</MaxScaleDenominator>
          <RasterSymbolizer>
            <Opacity>1.0</Opacity>
          </RasterSymbolizer>
        </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

```

**Comment by kalxas** [comment]
Relative issue:

https://gis.stackexchange.com/questions/27472/geoserver-geowebcache-showing-raster-layers-depending-on-scale-zoom-level

**Comment by kalxas** [comment]
Implemented as layer group in GeoServer. Some example requests:

http://beta.geoportal.ypen.gr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2177317.762178631034,3123616.742840894032,3611821.200355587993,6158143.246676764451&CRS=EPSG:3857&WIDTH=417&HEIGHT=881&LAYERS=basemap%3Abasemap_gys&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

http://beta.geoportal.ypen.gr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2468865.517361747567,4420688.289290538058,2939831.109613368753,4779519.216720344499&CRS=EPSG:3857&WIDTH=1155&HEIGHT=880&LAYERS=basemap%3Abasemap_gys&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

http://beta.geoportal.ypen.gr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2598839.787950668484,4540264.618232345209,2716581.186013574712,4629972.35008979775&CRS=EPSG:3857&WIDTH=1155&HEIGHT=880&LAYERS=basemap%3Abasemap_gys&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

http://beta.geoportal.ypen.gr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=2625038.523277219385,4562589.610592325218,2683909.222308672965,4607443.476521051489&CRS=EPSG:3857&WIDTH=1156&HEIGHT=880&LAYERS=basemap%3Abasemap_gys&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

**Comment by kalxas** [comment]
![image](https://user-images.githubusercontent.com/383944/153201019-41a0d5b3-c864-444b-8a49-6697e554059f.png)

**Comment by kalxas** [comment]
Available as default in http://beta.geoportal.ypen.gr/geonetwork/srv/eng/catalog.search#/map

**Comment by kalxas** [comment]
Link about changing the base layer in the GeoNetwork UI

https://www.geocat.net/setting-up-geonetwork-with-dutch-pdok-tile-services/

**Comment by grigoriouelena** [comment]
The Editor Map was changed also, using the same configuration as the other maps in the catalog.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/55238073/153868068-6e1a7bf0-b114-4e5a-9111-f5fd59e6e790.png">

The result is this:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/55238073/153868148-8a140bbb-8321-479b-97b6-e4b00fff3c19.png">
(visible when editing a metadata record)

Unfortunately, I did not find any information on changing the background map of the spatial extent thumbnail in the metadata view.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/55238073/153868339-66d7d4d8-6271-4902-81f3-40d73132577f.png">


Could the info found [here](https://geonetwork-opensource.org/manuals/trunk/eng/users/customizing-application/creating-custom-view.html) be any relevant?

**Comment by kalxas** [comment]
No, we have already applied this change.

**Comment by kalxas** [comment]
https://sourceforge.net/p/geonetwork/mailman/geonetwork-users/thread/CA%2B%3DcGJkKoCyaJz8pSVD2moHnNRNbHvUO59%2B6KiPmeWXPZ6nZCw%40mail.gmail.com/#msg35220815

**Comment by grigoriouelena** [comment]
As I understand, this is something we cannot change at the moment.

Before we close the issue, I noticed that when the user zooms in until there are no available tiles for the zoom level, the map disappears.
Is it possible to limit the zoom to the zoom level of the available tiles?

And, finally, is it possible to configure the basemap to its actual extent when the user clicks on "Zoom to initial map extent"?
![image](https://user-images.githubusercontent.com/55238073/154016893-83e65eb3-f6bd-4c47-afd7-0182219ce35e.png)

**Comment by kalxas** [comment]
> Before we close the issue, I noticed that when the user zooms in until there are no available tiles for the zoom level, the map disappears. Is it possible to limit the zoom to the zoom level of the available tiles?

I do not see this option in the GeoNetwork UI

> 
> And, finally, is it possible to configure the basemap to its actual extent when the user clicks on "Zoom to initial map extent"? 

I am going to look into this.

**Comment by kalxas** [comment]
Adding some default extents:

![image](https://user-images.githubusercontent.com/383944/154073441-3cbf4708-c7ca-4e21-a998-9f6328d77cb7.png)

The resolutions "add" option does not seem to work.

**Comment by kalxas** [comment]
> > Before we close the issue, I noticed that when the user zooms in until there are no available tiles for the zoom level, the map disappears. Is it possible to limit the zoom to the zoom level of the available tiles?
> 
> I do not see this option in the GeoNetwork UI

The "Resolutions" field is inactive in the UI Settings

> 
> > And, finally, is it possible to configure the basemap to its actual extent when the user clicks on "Zoom to initial map extent"?
> 
> I am going to look into this.

This does not seem to respect the bbox given in the UI Settings

**Comment by kalxas** [comment]
basemap_gys layer group re-configured
