### ISSUE TITLE
WFS validation

### ISSUE THREAD

**Issue by grigoriouelena** [EOFarm/geoportal.ypen.gr#27]
current implementation based on WB best practice
=================================
use of indentifiers in dataset & service metadata and in wfs caps
---------------------------------------------------------------------------------
**dataset metadata fileIdentifier**: uuid (eg. 5b0b577c-d79d-4d72-9322-0ef3835e22bb)
**dataset metadata <gmd:MD_dataIdentification> id attribute**: the code of the Unique Resource Identifier (eg. test)
**dataset metadata <gmd:MD_Identifier>**: Unique Resource Identifier (eg. http://nsdi.gov.gr/set/dataset/MINENV/test)

**service metadata <srv:operatesOn> uuidref attribute**: uuid (eg. 5b0b577c-d79d-4d72-9322-0ef3835e22bb)
**service metadata <srv:operatesOn> xlink:href attribute**: dataset metadata getRecordById response (http://beta.geoportal.ypen.gr/geonetwork/srv/eng/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;ID=5b0b577c-d79d-4d72-9322-0ef3835e22bb)

**WFS extended capabilities configuration in geoserver - code**: Unique Resource Identifier code part (eg. test)
**WFS extended capabilities configuration in geoserver - namespace**: Unique Resource Identifier namespace part (http://nsdi.gov.gr/set/dataset/MINENV/)
**WFS extended capabilities configuration in geoserver - Metadata URL**: dataset metadata getRecordById response (http://beta.geoportal.ypen.gr/geonetwork/srv/eng/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;ID=5b0b577c-d79d-4d72-9322-0ef3835e22bb)

Validation test FAILS
![image](https://user-images.githubusercontent.com/55238073/163148573-5cd84ec0-6e3a-4407-944c-6e38b502cc43.png)

proposed implementation
=================
It seems that the validator is expecting to find in the capabilities of the WFS (<srv:operatesOn>), the use of the gmd:MD_Identifier instead of the <gmd:fileIdentifier>.

If we fix that, the validator is able to restore the linkage between the dataset and the corresponding service.
![image](https://user-images.githubusercontent.com/55238073/163151965-4863bc83-d62a-46aa-8b5f-3cd53ed5b5c2.png)

The problem that is introduced with that change is that Geonetwork is relating dataset metadata with service metadata using the <srv:operatesOn> uuidref attribute and is expecting this to be the fileIdentifier. With the proposed change, Geonetwork does not relate the dataset with the service metadata in the geoportal GUI.
[https://geonetwork-opensource.org/manuals/trunk/fr/user-guide/associating-resources/linking-dataset-or-service.html](url)
[https://github.com/geonetwork/core-geonetwork/issues/2463](url)

validator problem
============
The above tests were succesful using the local validator (beta.geoportal.ypen.gr/validator), which is the latest 2021 release.
The current INSPIRE 2022.0 release of the validator has inreoduced the problem described [here] (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/718)issue)

It is proposed to move to the new configuration, and wait  for possible fixes from the Geonetwork and the INSPIRE validator community.

**Comment by kalxas** [comment]
@grigoriouelena can we please close this as it was fixed upstream?
