### ISSUE TITLE
D-2021-5 Deployment of INSPIRE Validator and OGC SOS services in development environment

### ISSUE THREAD

**Issue by kalxas** [EOFarm/geoportal.ypen.gr#5]
- [x] Deploy and configure INSPIRE Validator
- [x] Deploy and configure 52N SOS service
- [x] Report

**Comment by grigoriouelena** [comment]
https://github.com/INSPIRE-MIF/helpdesk-validator/releases

**Comment by kalxas** [comment]
https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.1
